quarkus:
  http:
    port: 8091
  native:
    additional-build-args:
      - --allow-incomplete-classpath
      - --initialize-at-run-time=org.apache.http.impl.auth.NTLMEngineImpl
  log:
    level: INFO
  mongodb:
    connection-string: mongodb://localhost:27018
    database: fileData

bot:
  username: test
  token: test
