quarkus:
  http:
    port: 8091
  native:
    additional-build-args:
      - --allow-incomplete-classpath
      - --initialize-at-run-time=org.apache.http.impl.auth.NTLMEngineImpl
  log:
    level: INFO
  mongodb:
    connection-string: mongodb://localhost:27018
    database: logData

minio:
  use-ssl: false
  host: 127.0.0.1
  port: 9000
  access-key: testtest
  secret-key: testtest

bot:
  username:
  token:
